### ISSUE TITLE
PRACTICA MULTIPLES IMAGENES

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/cs-equipo-magaly#1]
[MULTIPLES IMAGENES.pdf](https://github.com/SistemasTecTlaxiaco/cs-equipo-magaly/files/15202458/MULTIPLES.IMAGENES.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
